### DISCUSSION TITLE
oauth2 implicit flow enable custom redirect_uri and response_type(token/code)

### DISCUSSION THREAD

**Discussion by MukundMohanan** [scalar/scalar#1878] [Ideas]
I would like to integrate scalar API documentation with OAuth2 and host it on GitHub Pages.
Although my API endpoint requires Authorization Bearer `code`, currently it is not possible for me to use "implicit:flow" under securitySchema in Scalar because when I input my client-id, pop up appears with `authorizationUrl?redirectUrl=<window.location.href>`.

As mentioned above, my redirectUri would be pointing to GitHub Pages which is not my actual redirect_uri.
Also my OAuth systems response_types_supported is only "code".

https://github.com/scalar/scalar/blob/32b08ad05338ea01b945bcef0d68f53d47a66d62/packages/api-client/src/components/ApiClient/Request/RequestAuthentication/SecurityScheme.vue#L88-L92

![Preview](https://github.com/scalar/scalar/assets/32845021/ad05fd9a-2221-4d54-be78-2bff64e3cc62)

**Comment by hanspagel** [comment]
Interesting! Any chance you could share the specification or the security part?

If the redirect goes somewhere else, we can’t fetch the token, or am I missing something? 🤔

**Comment by MukundMohanan** [comment]
Hi @hanspagel 

```yml
  securitySchemes:
    oauth2:
      type: "oauth2"
      flows:
        implicit:
          authorizationUrl: https://<idp-domain>/authorization.oauth2
          tokenUrl: https://<idp-domain>/token.oauth2
          redirectUri: https://<my-domain>/login
          responseType: code
          scopes:
            openid: openid
```

After Client-ID input in UI and clicking on Authorize, the window pop up should take me to
`https://<idp-domain>/authorization.oauth2?redirect_uri=https://<my-domain>/login&client_id=&response_type=code`
upon successful authentication, it provides access token.

Please note that redirectUri is configured in IDP (Identity Provider) but due to current static redirect_uri in Scalar I get Invalid redirect_uri in the response

![Preview](https://github.com/scalar/scalar/assets/32845021/5b46e157-81f6-4a49-addf-e01817cd3a38)

Found another issue to discuss but share your thought if I should open up another discussion thread for this

This also is Authorization Code flow under security-schema but in Scalar Swagger preview it doesnt show up
https://sandbox.scalar.com/e/fKDQC

or maybe I'm wrong with the securitySchema authorizationCode.
