### DISCUSSION TITLE
How to add navbar on Hono API Reference?

### DISCUSSION THREAD

**Discussion by insiderins** [scalar/scalar#2032] [Q&A] [answered]
Hi mr @amritk @tmastrom, I hope you have a great day 👋

I'm newbie here, can you tell me how to add navbar on Hono API Reference?
like this :

![Screen Shot 2024-06-12 at 1 06 48 PM](https://github.com/scalar/scalar/assets/147728736/e9a6688f-41c7-4d2d-989b-c2cac78a3af3)

when i'm lookup parameter in api reference don't have like showNavbar or something.

```JS
import { apiReference } from "@scalar/hono-api-reference";
export const web = new OpenAPIHono();

web.get(
    "/",
    apiReference({
        searchHotKey: "k",
        hideModels: true,
        showSidebar: true,
        theme: "bluePlanet",
        pageTitle: "Usman RestfulAPI Reference",
        spec: {
            url: "/v1/api",
        },
    })
);

export default web;
```
this is my scalar page preview :

![Screen Shot 2024-06-12 at 1 02 00 PM](https://github.com/scalar/scalar/assets/147728736/7cd1d6ac-a719-4b9a-8887-af52a66312e6)

can you add a custom parameter like "showNavbar" and icon or logo? or tell me how to adding it

**Comment by hanspagel** [comment]
There’s no such thing in the open source package yet, the screenshot is from https://scalar.com/ (our hosted offering) that comes with a navigation bar. 

I’m pretty sure we’ll add a navigation bar to the open source package at some point, but it’ll take some time. ✌️ Meanwhile, you can add a simple header like shown below. Hope that helps!

https://codepen.io/hanspagel/pen/GRaMzzE

```html
<main class="main">
  
  <header class="my-custom-header">
    My Logo
  </header>

  <div class="container">
  <script
    id="api-reference"
    data-url="https://cdn.jsdelivr.net/npm/@scalar/galaxy/dist/latest.yaml"
    data-proxy-url="https://proxy.scalar.com"
  ></script>

  <script src="https://cdn.jsdelivr.net/npm/@scalar/api-reference"></script>
  </div>
  
</main>
```

```css
.my-custom-header {
  background: var(--scalar-background-1);
  color: var(--scalar-color-1);
  font-family: var(--scalar-font);
  padding: 20px;
  border-bottom: 1px solid var(--scalar-border-color);
}

.main {
  display: flex;
  flex-direction: column;
  font-family: sans-serif;
  box-sizing: border-box;
  width: 100vw;
  height: 100vh;
}
.container {
  flex: 1;
  overflow: hidden;
}
```
