### DISCUSSION TITLE
How to make external file references work

### DISCUSSION THREAD

**Discussion by krystof-k** [scalar/scalar#3427] [Q&A]
Hi, I can't make external file references work :( I'm always getting this error

```yaml
- 
  code:    EXTERNAL_REFERENCE_NOT_FOUND
  message: Can’t resolve external reference: ./pet.yaml
```

Is there some example I can follow please?

**Comment by hanspagel** [comment]
Sure! You’re using the CLI? Which command are you running? Let me debug this.

**Reply by krystof-k** [reply]
Yes. For example `validate`. I was just trying to extract the pet to separate `pet.yaml`:

```yaml
type: object
required:
  - id
  - name
properties:
  id:
    type: integer
    format: int64
  name:
    type: string
  tag:
    type: string
```

And then something like

```yaml
components:
  schemas:
    Pet:
      $ref: "./pet.yaml"
```

**Comment by hanspagel** [comment]
Damn, I found a bunch of smaller bugs in some of the more complex areas. Looks like I introduced a few of them over the last weeks without noticing. I’ve put up a PR so you can follow the progress: https://github.com/scalar/scalar/pull/3460

**Reply by krystof-k** [reply]
Awesome. Will do. Thanks!

**Reply by ersnover** [reply]
Hi! This issue seems to be popping up again. I have a similar spec structure to @krystof-k, with a mix of direct references to files and referencing an index file. I'm seeing the EXTERNAL_REFERENCE_NOT_FOUND errors for both types of reference. I'm using both `validate` and `dereference`, but also seeing the behavior using the HTML API documentation.

```yaml
paths:
  /users/data:
    $ref: 'user_data.yml#/paths/~1users~1data'
components:
  schemas:
    $ref: './schemas/_index.yml'
```

I dug around in the package code a bit and it looks like makeFilesystem doesn't have any logic to look beyond the entrypoint file when generating a new filesystem object. Is there a way to pass in multiple files for a specification that I'm missing, or is this a bug?

Thanks in advance!
