### DISCUSSION TITLE
Mermaid support && Colorized callouts

### DISCUSSION THREAD

**Discussion by derkan** [scalar/scalar#4279] [Ideas]
Please consider adding documentation on how to add mermaid support from [here](https://github.com/scalar/scalar/discussions/3477#discussioncomment-11604786). 

You may also consider it to add to main constructor of scalar with passing a configuration parameter (i.e: `mermaid_script=...mermaid.min.js` and if  `mermaid_script` source is defined, then init it automatically).

**Comment by derkan** [comment]
Bonus, colorize Callouts. 

![image](https://github.com/user-attachments/assets/b6030201-0620-43a5-b424-7c44d88d789e)


Put this code in javascript in [javascript code](https://github.com/scalar/scalar/discussions/3477#discussioncomment-11604786) like:

```javascript
....same

// Colorize callouts.
        // Usage:
        //
        // > [!success] Success
        // > This is a success message.
        async function renderCallouts() {
            const calloutBlocks = Array.from(document.querySelectorAll("blockquote"));

            const renderNext = async () => {
                if (calloutBlocks.length === 0) return;

                const block = calloutBlocks.shift();
                if (block.dataset.rendered) return renderNext();

                let content = block.textContent.trim();

                try {
                    // Match [!class] Title here
                    const match = content.match(/^\[!(\w+)\]\s*(.*)/);

                    if (match) {
                        const calloutClass = match[1].toLowerCase(); // e.g., success, info, warning, error
                        const titleText = match[2] || calloutClass.charAt(0).toUpperCase() + calloutClass.slice(1);

                        // Add the callout class to blockquote
                        block.classList.add(calloutClass);

                        // Create the title container
                        const titleP = document.createElement("p");
                        titleP.classList.add("title");
                        titleP.innerHTML = `<strong>${titleText}</strong>`;

                        // Remove the first line (marker and title) from the blockquote content
                        block.innerHTML = block.innerHTML.replace(match[0], "").trim();

                        // Insert the title at the top of the blockquote
                        block.insertBefore(titleP, block.firstChild);
                    }

                    block.dataset.rendered = true;
                } catch (err) {
                    console.error("Callout rendering failed:", err);
                    block.innerHTML = `<pre>Error rendering callout: ${err.message}</pre>`;
                } finally {
                    requestAnimationFrame(renderNext); // Schedule the next block
                }
            };

            renderNext();
        }


        // Render mermaids
        // Usage:
        //
        // ```mermaid
        // 		%%%%{init: {'theme': 'dark', 'themeVariables': {'edgeLabelBackground':'#333'}}}%%%%
        // graph TD;
        //     A-->B;
        //     A-->C;
        //     B-->D;
        //     C-->D;
        // ```
        async function renderMermaidDiagrams() {
            renderCallouts()
... same
```

## CSS

```css
/* Base blockquote styling */
blockquote {
    border-left: 5px solid #555 !important;
    padding: 15px 20px !important;
    background-color: #222 !important;
    color: #ddd !important;
    border-radius: 8px !important;
    font-size: 1rem !important;
    margin: 20px 0 !important;
    position: relative !important;
    display: flex !important;
    flex-direction: column !important;
    gap: 5px; /* Adds space between title and text */
}

/* Highlighted title styles */
blockquote strong {
    display: block !important;
    font-weight: bold !important;
    margin-bottom: 5px !important;
    font-size: 1.1rem !important;
    line-height: 1.2 !important;
}

/* Fix alignment for titles and text */
blockquote p {
    margin: 0 !important;
    line-height: 1.5 !important;
}

/* Icons for callouts */
blockquote::before {
    font-size: 1.5rem !important;
    font-weight: bold !important;
    position: absolute !important;
    top: 10px !important;
    left: 15px !important;
}

/* Success */
blockquote.success {
    border-left-color: #28a745 !important;
    background-color: #103820 !important;
    color: #a3e7af !important;
}

blockquote.success::before {
    content: "👍" !important;
    color: #28a745 !important;
}

blockquote.success strong {
    color: #28a745 !important;
    margin-left: 20px;
    line-height: 20px!important;
}

/* Info */
blockquote.info {
    border-left-color: #17a2b8 !important;
    background-color: #0b3d4f !important;
    color: #9edff1 !important;
}

blockquote.info::before {
    content: "📘" !important;
    color: #17a2b8 !important;
}

blockquote.info strong {
    color: #17a2b8 !important;
    margin-left: 20px;
    line-height: 20px!important;
}

/* Warning */
blockquote.warning {
    border-left-color: #ffc107 !important;
    background-color: #332a11 !important;
    color: #f8e3a1 !important;
}

blockquote.warning::before {
    content: "⚠" !important;
    color: #ffc107 !important;
}

blockquote.warning strong {
    color: #ffc107 !important;
    margin-left: 20px;
    line-height: 20px!important;
}

/* Error */
blockquote.error {
    border-left-color: #dc3545 !important;
    background-color: #3d1a1a !important;
    color: #f5b5b5 !important;
}

blockquote.error::before {
    content: "❗" !important;
    color: #dc3545 !important;
}

blockquote.error strong {
    color: #dc3545 !important;
    margin-left: 20px;
    line-height: 20px!important;
}

/* Ensure spacing between consecutive blockquotes */
blockquote + blockquote {
    margin-top: 20px !important;
}
```

Use callouts like this:

```markdown

> [!success]
> This is a success message.

> [!info]
> This is an informational message.

> [!warning]
> This is a warning message.

> [!error]
> This is a warning message<br>
> This is a warning message. 
	
```
