### DISCUSSION TITLE
Add pre/post request scripts

### DISCUSSION THREAD

**Discussion by marclave** [scalar/scalar#7790] [Ideas]
### **Description:**

* Need to have optional user scripts run pre/post

```yaml
x-scalar-scripts: 
  some-script-name:
    id: string,
    code: string,
    typescript: boolean,
        - required: false

some-operation:
  # Array of scripts to run in the array order
  x-scalar-post-scripts: 
    - $ref/some-script-name
    - $ref/some-other-script
  x-scalar-pre-scripts:
    - $ref/some-script-name
```

```typescript
type RequestScript = {
  uid: string,
  /** Unique name to key them in the collection */
  name: string,
  /** User input string */
  rawString: string,
  /** Santized, transpiled, and formatter string to execute */
  codeString: string,
  /** We should offer on the fly TS transpilation */
  isTypescript: boolean,
}

type PreRequestOperation = async (request: RequestInit) => RequestInit
type PostRequestOperation = async (response: Response) => any
```

**Acceptance Criteria:**

* Users are able to add requests
* Requests are properly serialized back to the OpenAPI spec
