### ISSUE TITLE
OAuth Authorization Code bug

### ISSUE THREAD

**Issue by x-delfino** [scalar/scalar#1960]
### What happens?

When using `@scalar/api-reference-react@0.1.96` (`@scalar/api-reference@1.22.54`)  or later - `g.value.flows.password is undefined` is thrown when using Authorization Code security scheme.

It looks like https://github.com/scalar/scalar/pull/1862 caused this issue

### What did you expect to happen?

I'm assuming support for this flow will come at some point however the unsupported schemes should be ignored until supported. I can try and look at raising a PR, however I can see that work on the OAuth functionality is ongoing (e.g. https://github.com/scalar/scalar/pull/1949)

### How can we reproduce the issue?

1. Create schema with Authorization Code scheme:
```yaml
components:
  securitySchemes:
    OAuth2:
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: https://example.com
          tokenUrl: https://example.com
          scopes:
            scope: scope
```
2. Use schema with `@scalar/api-reference-react@0.1.95`/`@scalar/api-reference@1.22.53` - everything works fine.
3. Use schema with `@scalar/api-reference-react@0.1.96`/`@scalar/api-reference@1.22.54`, `g.value.flows.password is undefined` is thrown

### OpenAPI Document

https://sandbox.scalar.com/e/6mZtB
