### ISSUE TITLE
Parameter details are missing example

### ISSUE THREAD

**Issue by oxtoacart** [scalar/scalar#1971]
### What happens?

My OpenAPI spec contains a parameter like the below

```
actor:
      name: actor
      in: query
      description: list of filters on actors, either exact actor IDs or a wildcard search on login name or display name indicated as `~search`
      required: false
      schema:
        type: array
        items:
          type: string
        example: [uc4p8fRHvJ11KTM59, ~bob]
```

The query parameters entry for that parameter does not show the example

<img width="642" alt="image" src="https://github.com/scalar/scalar/assets/5000654/993e64a1-2ffd-4d32-bd75-6c3043f0ccee">

### What did you expect to happen?

If I render the same spec with Redocly, it does show the example.

<img width="826" alt="image" src="https://github.com/scalar/scalar/assets/5000654/9f9fa7d1-c350-4ae9-9f79-68015f0f26b0">

### How can we reproduce the issue?

1. Write an OpenAPI spec that includes a parameter with an example value
2. Render the Spec
3. See that the example is not shown
