### ISSUE TITLE
OAuth: Use authorizationUrl, tokenUrl and redirectUri properly

### ISSUE THREAD

**Issue by hanspagel** [scalar/scalar#1987]
```yml
  securitySchemes:
    oauth2:
      type: "oauth2"
      flows:
        implicit:
          authorizationUrl: https://<idp-domain>/authorization.oauth2
          tokenUrl: https://<idp-domain>/token.oauth2
          redirectUri: https://<my-domain>/login
          responseType: code
          scopes:
            openid: openid
```

After Client-ID input in UI and clicking on Authorize, the window pop up should take me to
`https://<idp-domain>/authorization.oauth2?redirect_uri=https://<my-domain>/login&client_id=&response_type=code`
upon successful authentication, it provides access token.

Please note that redirectUri is configured in IDP (Identity Provider) but due to current static redirect_uri in Scalar I get Invalid redirect_uri in the response

![Preview](https://github.com/scalar/scalar/assets/32845021/5b46e157-81f6-4a49-addf-e01817cd3a38)

Found another issue to discuss but share your thought if I should open up another discussion thread for this

This also is Authorization Code flow under security-schema but in Scalar Swagger preview it doesnt show up
https://sandbox.scalar.com/e/fKDQC

or maybe I'm wrong with the securitySchema authorizationCode.

_Originally posted by @MukundMohanan in https://github.com/scalar/scalar/discussions/1878#discussioncomment-9596555_
