### ISSUE TITLE
Description of properties not loading using CDN version

### ISSUE THREAD

**Issue by rajnandan1** [scalar/scalar#290]
### Expected Behavior

OpenAPI version: 3.0.0
This is a property `name` and it has a description.

```
NewPet:
  type: "object"
  required:
    - "name"
  properties:
    name:
      type: "string"
      description: "some desc"
    tag:
      type: "string"
```

UI does not load description
<img width="629" alt="Screenshot 2023-10-18 at 11 37 22 AM" src="https://github.com/scalar/scalar/assets/16224367/ccddbf3c-7bea-4392-8e2f-79293ffeb37f">

Full html

```
<!DOCTYPE html>
<html>
  <head>
    <title>Swagger Petstore - API Reference</title>
    <meta charset="utf-8" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1" />
    
  </head>
  <body>
    <!-- Add your own OpenAPI/Swagger spec file URL here: -->
    <script
      id="api-reference"
      data-url="/json/raj12/pet_store.json"></script>
    <script src="https://www.unpkg.com/@scalar/api-reference"></script>
  </body>
</html>```



### Actual Behavior

Description to come in the UI

 


### Version

CDN

### What browsers are you seeing the problem on?

Chrome, Firefox
