### ISSUE TITLE
parameter example value are not retrieved

### ISSUE THREAD

**Issue by antlio** [scalar/scalar#3456]
### What happens?

It seems like the api client is not retrieving the parameter example, and yet not display it as a query parameter table value:

```yaml
  parameters:
  - example: example value
    in: query
    name: parameter_name
    required: true
    type: string
```

### What did you expect to happen?

<img width="828" alt="image" src="https://github.com/user-attachments/assets/4d588966-fa24-4d10-9dfe-a88deffa7b8c">

**Comment by amritk** [comment]
I think hans may have fixed this one already

**Comment by marclave** [comment]
@amritk @antlio confirmed fixed in latest release
![image](https://github.com/user-attachments/assets/64edc5be-30b9-4072-9338-9d41b1451427)

**Comment by kovapatrik** [comment]
I'm still experiencing this issue while using the HTML API Reference. I have some query params defined, for example:

```yaml
- name: user-id
  in: query
  required: true
  schema:
    type: string
    format: uuid
  example: 00000000-0000-0000-0000-000000000001
  x-go-name: UserIDQueryParam
  x-oapi-codegen-extra-tags:
    validate: "required,uuid"
```

In the API reference I can see this example in the curl command for example: 
![image](https://github.com/user-attachments/assets/ad7e3bc6-1f52-4a11-b38c-e553229ed6c1)

But it's not filled when opening the API client:
![image](https://github.com/user-attachments/assets/1d1142e6-995b-489a-a26e-8804bbf8952f)
