### ISSUE TITLE
Parsing example values for parameters broke with v1.25.53

### ISSUE THREAD

**Issue by kovapatrik** [scalar/scalar#3760]
### What happens?

I have a query parameter defined in one of my endpoints like this:
```yaml
- name: currency-id
  in: query
  required: true
  schema:
    type: string
    format: uuid
  example: a26cdf3a-6e70-9124-385d-4d7eb9bff6b8
  x-go-name: CurrencyIDQueryParam
  x-oapi-codegen-extra-tags:
    validate: "required,uuid"
```
If I try to pass this (alongside with the whole openapi definition of course) to scalar, I'm getting an error upon loading the HTML reference page in the console:
```
standalone.js:3129 {
  "_errors": [],
  "parameters": {
    "0": {
      "_errors": [],
      "examples": {
        "_errors": [],
        "default": {
          "_errors": [
            "Expected object, received string"
          ]
        }
      }
    },
    "1": {
      "_errors": [],
      "examples": {
        "_errors": [],
        "default": {
          "_errors": [
            "Expected object, received string"
          ]
        }
      }
    },
    "2": {
      "_errors": [],
      "examples": {
        "_errors": [],
        "default": {
          "_errors": [
            "Expected object, received number"
          ]
        }
      }
    },
    "_errors": []
  }
}
```
It also logs out the problematic object:
```json
{
    ...
    "parameters": [
        ...
        {
            "name": "currency-id",
            "in": "query",
            "required": true,
            "schema": {
                "type": "string",
                "format": "uuid"
            },
            "x-go-name": "CurrencyIDQueryParam",
            "x-oapi-codegen-extra-tags": {
                "validate": "required,uuid"
            },
            "examples": {
                "default": "a26cdf3a-6e70-9124-385d-4d7eb9bff6b8"
            }
        },
        ...
    ],
    ...
}
```
As you can see, if I use the singular `example` tag to define an example for my parameter, it transforms into the `examples` one, but the content of it is wrong.

### What did you expect to happen?

Either the transformed value should be:
```json
"examples": {
    "default":  {
        "value": "a26cdf3a-6e70-9124-385d-4d7eb9bff6b8"
    }
 }
```
or there shouldn't be any transformation at all for singular examples.
