### ISSUE TITLE
Can't fill a single Auth schema if there are multiple with same `type`

### ISSUE THREAD

**Issue by fenix-hub** [scalar/scalar#3887]
### What happens?

I'm using the scalar ui from my angular application and i want to show and autofill api tokens for an openapi spec that has two mandatory authorization schemas. Both of them are of type 'apiKey' but with different names. Id like to autofill just one of them and keep the other one empty, but im only able to fill both of them or none. How do I configure it?

example schema:
```
securitySchema:
 X-Domain-ApiKey:
  in: header
  name: apikey1
  type: apiKey
 X-Domain-Host:
  in: header
  name: apikey2
  type: apiKey
```

example configuration:
```
authentication: {
 apiKey: {
 token: "xyz"
 }
}
```

### What did you expect to happen?

I expected to fill just one of them, and not both of them
