### ISSUE TITLE
TypeError: e.trim is not a function in 200 array response

### ISSUE THREAD

**Issue by vladimirvolek** [scalar/scalar#4438]
### What happens?

The error:
```
Oops, something went wrong here.
TypeError: e.trim is not a function
```

1. Go to https://docs.blockfrost.io/#tag/cardano--network/GET/network/eras
2. Click on `Expand 200 Returns era summaries content.`

Error in 200 response only if it's an array
```yaml
type: array
items:
  type: object
  properties:
    time:
      type: integer
      description: Starting time of the call count interval (ends midnight UTC) in UNIX time
    calls:
      type: integer
      description: Sum of all calls for a particular day
  required:
    - time
    - calls
example:
  - time: 1612543884
    calls: 42
  - time: 1614523884
    calls: 6942

```

### What did you expect to happen?

Show the response

**Comment by vladimirvolek** [comment]
Same in `metrics`

https://docs.blockfrost.io/#tag/metrics

```yaml
type: array
items:
  type: object
  properties:
    time:
      type: integer
      description: Starting time of the call count interval (ends midnight UTC) in UNIX time
    calls:
      type: integer
      description: Sum of all calls for a particular day
  required:
    - time
    - calls
example:
  - time: 1612543884
    calls: 42
  - time: 1614523884
    calls: 6942

```
