### ISSUE TITLE
Scalar is not properly observing explode variable of array property

### ISSUE THREAD

**Issue by milek** [scalar/scalar#4975]
### What happens?

Setting `explode` on property in query does nothing in Scalar. 

There is an inconsistency to behaviour of array types in query. While browser shows comma separated request in code snippets, client will send multiple variables of the same name. Setting `explode` does not change this behaviour.

### What did you expect to happen?

- Setting `explode` to `true` should show in browser that multiple variables in query will be send to the server.
- Setting `explode` to `false` should instruct client to send comma separated values to single variable in query

**Comment by hanspagel** [comment]
Oh, true, great report! We don’t support `explode` yet.

Read more about `explode` here: https://github.com/OAI/OpenAPI-Specification/blob/main/versions/3.1.1.md

**Comment by calebpanza** [comment]
Is there any progress on this by any chance? Running into a similar issue where I'm expecting it to respect `explode` but it's not

**Comment by Diggsey** [comment]
Looks like this was fixed in https://github.com/scalar/scalar/pull/5678 !

**Comment by amritk** [comment]
Where were you looking for this to be fixed? Got a PR up to fix it in the code snippets which handles all of the styles, we can apply this elsewhere as well!

https://github.com/scalar/scalar/pull/5930/files#diff-4a3d157d2bc7a64a940e720172e7876c65b3bfa2b517dedff83c6e79fc7b92a1

**Comment by monolithed** [comment]
```yaml
components:
        Categories:
            name: category
            in: query
            style: form
            explode: true
            required: true
            schema:
                type: array
                items:
                    type: string
                    enum:
                        - foo
                        - bar
                    examples:
                        - category=foo&category=bar

```

Output:

```
/api/v1/category=%3Fcategory%3Dfoo%26category%3Dbar
```

It looks a bit weird, doesn’t it?
