### ISSUE TITLE
`x-enumDescriptions` not rendered

### ISSUE THREAD

**Issue by TimoGlastra** [scalar/scalar#4983]
### What happens?

The `x-enumDescriptions` property is not rendered.

Looking at the code, it checks whether the property is an array, but I think according to the docs it must be an object (it used the enum value as the lookup property).

https://github.com/scalar/scalar/blob/479a2efb8dce6023c81b8a6469e27535a572ae85/packages/api-reference/src/components/Content/Schema/SchemaProperty.vue#L222

### What did you expect to happen?

The labels from `x-enumDescriptions` are rendered

### OpenAPI Document

https://sandbox.scalar.com/e/R4UdC

**Comment by reggie-pierce-impilo** [comment]
I can confirm that this _does not_ work:

```
    DimensionUnit:
      enum:
      - in
      - cm
      type: string
      x-enumDescriptions:
        in: Inches.
        cm: Centimeters.
```

nor:

```
    DimensionUnit:
      enum:
      - in
      - cm
      type: string
      x-enumDescriptions:
      - Inches.
      - Centimeters.
```

nor:

```
    DimensionUnit:
      enum:
      - in
      - cm
      type: string
      x-enumDescriptions:
      - in: Inches.
      - cm: Centimeters.
```

chatgpt says:

### 🛠 TL;DR Fix

#### 1. Your OpenAPI:
```yaml
DimensionUnit:
  type: string
  enum:
    - in
    - cm
  x-enumDescriptions:
    in: Inches.
    cm: Centimeters.
```

#### 2. Your Vue template fix:
```vue
<template v-if="optimizedValue?.['x-enumDescriptions'] && typeof optimizedValue['x-enumDescriptions'] === 'object'">
  <div class="property-list">
    <div
      v-for="enumValue in getEnumFromValue(optimizedValue)"
      :key="enumValue"
      class="property">
      <div class="property-heading">
        <div class="property-name">
          {{ enumValue }}
        </div>
      </div>
      <div class="property-description">
        <ScalarMarkdown
          :value="optimizedValue['x-enumDescriptions'][enumValue]" />
      </div>
    </div>
  </div>
</template>
```

Let me know if you want a patch or pull request-ready version.
