### ISSUE TITLE
Format `byte` is not migrated

### ISSUE THREAD

**Issue by matthyk** [scalar/scalar#5272]
### What happens?

Binary format `byte` is ignored.
```yaml
content:
   image/png:
      schema:
         type: 'string',
         format: 'byte'
```

is not transformed/upgraded properly. 

### What did you expect to happen?

The `byte` format should be upgraded to the usage of `contentMediaType` and `contentEncoding`. See [here](https://swagger.io/specification/#working-with-binary-data) for the relevant section of the OpenAPI specification.

```yaml
content:
   image/png:
      schema:
         type: 'string',
         format: 'byte'
```
should be transformed to
```yaml
content:
   image/png:
      schema:
         type: 'string',
         contentMediaType: 'image/png',
         contentEncoding: 'base64'
```
