### ISSUE TITLE
Schema references with overlapping sibling keywords not handled correctly

### ISSUE THREAD

**Issue by handrews** [scalar/scalar#5582]
### What happens?

This OAD:

```YAML
openapi: 3.1.1 
info:
  version: 1.0.0 
  title: Test schema $ref with siblings
paths:
  /foo: 
    get:  
      responses:
        "200":
          description: Ok
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Foo"
                pattern: "^foo"
components:
  schemas:
    Foo:  
      type: string
      pattern: "bar$"
```

uses JSON Schema draft 2020-12's ability to have keywords adjacent to `$ref`.  These _all_take effect, meaning that the response needs to be a string that both starts with `foo` and ends with `bar`.

However, Scalar only shows the `pattern: "^foo"` constraint.

### What did you expect to happen?

Both `pattern` constraints must be shown (and validated, used for code generation, etc.)

**Comment by handrews** [comment]
BTW, I'm not sure what goes here vs scalar/openapi-parser.  If this should be filed over there, please feel free to close and I can re-file with the right info in that repo.

**Comment by hanspagel** [comment]
Oh, I wasn’t aware that’s the case. I don’t really know how we’d deal with that. Maybe we should then keep an array of all those additional properties and apply all? Looks like that would make the whole rendering a lot more complex. Or is pattern just a special case, should everything else just overwrite (that part is easy to add)? 🤔 Any thoughts on this?

**Comment by handrews** [comment]
@hanspagel it's not a special case, I'm afraid.  The model for JSON Schema draft 2020-12 referencing is one of delegation, not of textual replacement (because people really didn't like that adjacent keywords were ignored / dropped, and textual replacement has _never_ generally worked in JSON Schema because of the need to support cyclic references).

To fully support JSON Schema references, even back in draft-04, you can't just remove and replace them.  You have to track their effects.

**Comment by handrews** [comment]
@hanspagel There are also complexities around the Path Item Object's `$ref` to consider (in all OAS versions), although that complexity is more amenable to textual replacement.

But in general, you can't quite do that in the OAS either, because the Link object's `operationRef` keyword and the URI form of the Discriminator Object's `mapping` are essentially `$ref`s that cannot be replaced.  In OAS 3.2, keys in the Security Requirement Object will also have a URI form analogous to how `mapping` works.

**Comment by hanspagel** [comment]
Submitted a PR to our new OpenAPI-based data source: #6111

We’re about to migrate to it, so it should be actually rendered very soon.

**Comment by DemonHa** [comment]
@handrews Hey Andrew, there are a couple of cases where I am not quite sure how we are supposed to handle.

When we resolve the refs, how are we supposed to return the combination of the properties, we can't handle that ourself.

We can return an array of all properties combined. If we take your example it should be:

```
pattern: ["^foo", "bar$"]
```

but we can't really do that because it will change the schema of the resolved property


Can you provide an example on how the resolved schema should look like that this particular example?

What about this case:

```
{
  a: {
    b: {
      $ref: "#/c",
      description: "This is a reference to the 'c' property"
    }
  },
  c: {
    d: "This is the 'd' property",
    description: "This is a reference to the 'c' property"

    e: {
      f: "This is the 'f' property"
    }
  }
}
```

**Comment by handrews** [comment]
@DemonHa if you'll bear with me for a minute, could you let me know if your implementation supports recursive schema references?  The valid kind where the finite instance will ensure the loop terminates?  A simple example:

```yaml
type: object
properties:
  data:
    $comment: Any value is allowed
  children:
    type: array
    items:
      $ref: "#"
```

This is a simple tree node schema with a data property and an array-of-children property, both of which are optional.

I promise that whether you support this is relevant to how I answer your question.

**Comment by DemonHa** [comment]
@handrews Yes, we do support recursive schema references, and we resolve them on the fly using a proxy.

**Comment by handrews** [comment]
Apologies for the delay in replying- I'm getting over a cold but I'll get back to you with the rest of the answer soon.

**Comment by DemonHa** [comment]
@handrews So sorry to hear that, hope you get better soon!

**Comment by handrews** [comment]
@DemonHa OK so the fact that you support cyclic references tells me that:

1. You understand that it has never been possible to implement referencing simply by replacing the source with the target
2. You have the correct general idea of proxying a schema to make it look like it is in one place (the _evaluation path_ or _[location path](https://www.ietf.org/archive/id/draft-bhutton-json-schema-01.html#name-collecting-annotations)_) while it actually is in another place (the _[absolute location](https://www.ietf.org/archive/id/draft-bhutton-json-schema-01.html#name-collecting-annotations)_) [^1]
3. Your difficulty is that you're still trying to "resolve" by creating a single schema from the source and the context, and treating that like it lives at the absolute location that held the `$ref`.  You need to keep them separate and make your proxying just a _bit_ smarter, so that it handles evaluation paths where you can't "remove" the reference from the path without losing information, because there are additional things at both the source absolute location (where the `$ref` is) and at the reference target.

Let's revisit our example and make it a bit more complex (hopefully I got all of this right- if something doesn't make sense please ask, I may have just messed it up):

```yaml
$id: https://example.com/tree
$defs:
  foo:
    pattern: foo
type: object
properties:
  data:
    $ref: "#/$defs/foo"
    pattern: bar
  children:
    type: array
    items:
      $ref: "#"
```

Say we want to evaluate this schema with the instance:

```yaml
data: foobar
children:
- data: barfoo
- data: foo
```

we end up with a series of evaluation steps for the `data` field that look like this (ignoring the steps for everything else — hopefully this format is self-explanatory):

```yaml
- instance location: /data
  keyword absolute location: https://example.com/tree#/$defs/foo/pattern
  keyword evaluation path: /properties/data/$ref/pattern
  valid: true
- instance location: /data
  keyword absolute location: https://example.com/tree#/properties/data/pattern
  keyword evaluation path: /properties/data/pattern
  valid: true
- instance location: /children/0/data
  keyword absolute location: https://example.com/tree#/$defs/foo/pattern
  keyword evaluation path: /properties/children/items/$ref/properties/data/$ref/pattern
  valid: true
- instance location: /children/0/data
  keyword absolute location: https://example.com/tree#/properties/data/pattern
  keyword evaluation path: /properties/children/items/$ref/properties/data/pattern
  valid: true
- instance location: /children/1/data
  keyword absolute location: https://example.com/tree#/$defs/foo/pattern
  keyword evaluation path: /properties/children/items/$ref/properties/data/$ref/pattern
  valid: true
- instance location: /children/1/data
  keyword absolute location: https://example.com/tree#/properties/data/pattern
  keyword evaluation path: /properties/children/items/$ref/properties/data/pattern
  valid: false
```

Note that the evaluation path includes `$ref`!  Let's pull those out and look at them:

```yaml
- /properties/data/pattern
- /properties/data/$ref/pattern
- /properties/children/items/$ref/properties/data/pattern
- /properties/children/items/$ref/properties/data/$ref/pattern
```

You're trying to "resolve" the schema so that that `$ref` isn't there, but a.) as you've noticed, not all keywords can be combined, and b.) if you can't combine the keywords, then if you don't treat the `$ref` as producing a distinct evaluation path, then you have a collision here, and you can't tell which `pattern` keyword you're trying to use.

So your proxy can't be quite as simple as making it _look_ there's a schema that "replaced" the reference.  The proxy needs to just implement `$ref` like a one-item `allOf` where the subschema is proxied.

Does that make sense?  It's critically important to keep the evaluation path and the absolute location separate, and not conflate evaluation paths because of how the references are arranged.  Sometimes the evaluation path is more important, and sometimes the absolute location is more important.  But you need to track both (this becomes even more important with `unevaluatedProperties`, `unevaluatedItems`, `$dynamicRef`, and collecting annotations).


[^1]: These locations are discussed in more detail under [output formats](https://www.ietf.org/archive/id/draft-bhutton-json-schema-01.html#name-minimum-information), although the terminology there is a bit confusing, using "keyword relative location" for what I'd call the evaluation path plus the keyword.

**Comment by amritk** [comment]
hey @handrews alright that makes sense we can track the data. But for display purposes what would we do when we have two description strings like in @DemonHa's [example](https://github.com/scalar/scalar/issues/5582#issuecomment-3029170886). What should the UI show in this case?

**Comment by handrews** [comment]
@amritk sorry for the delay I missed this somehow.  The OAS doesn't really mandate how displays work.  I would say that you should handle:

```YAML
components:
  schemas:
    Foo:
      pattern: foo
    Bar:
      pattern: bar
      $ref: "#/components/schemas/foo"
```

the same way you'd handle:

```YAML
components:
  schemas:
    Bar:
      pattern: bar
      allOf:
      - pattern: foo
```

unless you want to make it clear that there's a referenced/potentially shared schema involved.  But in terms of validation these are equivalent.  The only difference is the evaluation path, which does not change validation outcomes.
